<?php
/**
 * Created by PhpStorm.
 * Account: Luke
 * Date: 20/8/2018
 * Time: 10:46 PM
 */

namespace Module\OAuth\Handler\Facebook;


use Lib\Core\Helper\Db\Conn;
use Module\OAuth\Handler\IData;
use Swagger\Annotations\Items;

/**
 * Model
 * @property int $user_id
 * @property string $auth_method_id
 * @property string $data
 * @property string $data_search_field
 */
class Model extends \Module\OAuth\Handler\AbstractModel
{
    protected const METHOD = 'facebook';

    public static function load(int $member_id) {
        return self::_load('auth_method.name LIKE ? AND user_id=?','si',[self::METHOD,$member_id]);
    }

    public static function loadUserFromFacebookId(string $id) {
        return static::_load('data_search_field LIKE ? AND auth_method.name LIKE ?','ss',[$id,static::METHOD]);
    }

    public function __construct()
    {
        //$this->auth_method_id = \Module\OAuth\AuthMethod::loadByName(self::METHOD)->id();
        $this->auth_method_id = self::METHOD;
    }

    /**
     * @param Data $obj
     */
    public function setDataField(IData $obj)
    {
        parent::setDataField((object) $obj); // TODO: Change the autogenerated stub
        $this->data_search_field = $obj->facebookId;
    }


    /**
     * Get decoded json string as array
     * Create a respective getDataField() in child class
     * @return object
     */
    public function getDataField(): IData
    {
        if ($this->data_field_cache == NULL) {
            $this->data_field_cache = new Data((array) \json_decode($this->data));
        }
        return $this->data_field_cache;

    }
}