<?php
/**
 * Created by PhpStorm.
 * User: Luke
 * Date: 19/11/2018
 * Time: 4:04 PM
 */

namespace FileSystem\Type;
use Module\Exception\FileSystem;
use Module\FileSystem\File;

class Video extends File
{
    const MAX_SIZE = 50000000;

    CONST CLASS_HANDLER_FIELD = '\Module\FileSystem\Type\Video';

    public function save(bool $updateIfFound = true)
    {
        if (!isset($this->extension)) {
            throw new FileSystem("Extension and Mime property must be set");
        }
        if (\in_array($this->extension,\Config\File::ALLOWED_VIDEO_EXTENSIONS)) {
            return parent::save(); // TODO: Change the autogenerated stub
        }
        throw new FileSystem(FileSystem::INVALID_FILE_TYPE);
    }


    public function getUrl()
    {
        return \Config\File::DOMAIN . \Config\File::SAVE_PATH . '/videos' . $this->path;
    }
}