<?php


namespace Lib\Form\Value;


use Lib\Form\Value;

/**
 * Class Integer
 * @package Lib\Form\Value
 * @property int $data
 */
class Integer extends Value
{
    public static function getColumns()
{
    parent::getColumns(); // TODO: Change the autogenerated stub
    static::$_column_cache[static::$_column_data_index]->select_function = 'CONVERT(data,INTEGER) as data';
    static::$_column_cache[static::$_column_data_index]->type = 'i';
    return static::$_column_cache;
}


    public function _loadData(array $array)
    {

        parent::_loadData($array); // TODO: Change the autogenerated stub
        $this->data = intval($this->data);
    }

    /**
     * @return bool
     */
    public function isDataValid()
    {
        //var_dump($this->data);
        return \is_int($this->data) || \ctype_digit($this->data);
    }
}