<?php


namespace Lib\Form\Value;


use Lib\Form\Value;

/**
 * Class Json
 * @package Lib\Form\Value
 * @property object|array $data
 */
class Json extends Value
{
    public static function getColumns()
    {
        parent::getColumns(); // TODO: Change the autogenerated stub
        static::$_column_cache[static::$_column_data_index]->select_function = 'CONVERT(data  USING utf8mb4) as data';
        static::$_column_cache[static::$_column_data_index]->type = 's';
        return static::$_column_cache;
    }

    public function _loadData(array $array)
    {
        parent::_loadData($array); // TODO: Change the autogenerated stub
        $this->data = \json_decode($this->data);
    }

    /**
     * @return bool
     */
    public function isDataValid()
    {
        return \is_object($this->data) || \is_array($this->data);
    }


    public function preSave()
    {
        $this->data = \json_encode($this->data);
        parent::preSave(); // TODO: Change the autogenerated stub
    }

    public function save(bool $updateIfFound = true)
    {
        parent::save($updateIfFound); // TODO: Change the autogenerated stub
    }
}