<?php


namespace Lib\Form\Value;


use Lib\Form\Value;

class Number extends Value
{
    public static function getColumns()
    {
        parent::getColumns(); // TODO: Change the autogenerated stub
        static::$_column_cache[static::$_column_data_index]->select_function = 'CONVERT(data,double) as data';
        static::$_column_cache[static::$_column_data_index]->type = 'd';
        return static::$_column_cache;
    }
    /**
     * @return bool
     */
    public function isDataValid()
    {
        return \is_numeric($this->data);
    }
}