<?php

namespace Lib\Form\Value;


use Lib\Form\Value;

class StringValue extends Value
{
    public static function getColumns()
    {
        parent::getColumns(); // TODO: Change the autogenerated stub
        static::$_column_cache[static::$_column_data_index]->select_function = 'CONVERT(data USING utf8mb4) as data';
        static::$_column_cache[static::$_column_data_index]->type = 's';
        return static::$_column_cache;
    }
    /**
     * @return bool
     */
    public function isDataValid()
    {
        return \is_string($this->data);
    }
}