<?php
/**
 * Created by PhpStorm.
 * User: Luke
 * Date: 29/7/2018
 * Time: 5:28 PM
 */

namespace Lib\Core\Helper\Db;


class mysqli_stmt extends \mysqli_stmt {
    public function __construct($link, $query) {
        parent::__construct($link, $query);
    }

    /**
     * @param string $types
     * @param array $array
     * @return void
     */
    public function bind_param_array(string $types, array $array) {
        foreach($array as $key => $item) {
            $params[] = &$array[$key];
        }
        //var_dump($types);var_dump($params);
        $result = $this->bind_param($types,...$params);

        if (!$result) {
           throw new \Module\Exception\MySQL($this);
        }
    }

    public function execute()
    {
        $result = parent::execute(); // TODO: Change the autogenerated stub
        if (!$result) {
           // var_dump($this);
            throw new \Module\Exception\MySQL($this);
        }
        return true;
    }

    /**
     * @param $out
     * @return void
     */
    public function stmt_bind_assoc(&$out) {
        $data = \mysqli_stmt_result_metadata($this);
        $fields = array();
        $out = array();

        $fields[0] = $this;
        $count = 1;

        while($field = \mysqli_fetch_field($data)) {
            $fields[$count] = &$out[$field->name];
            $count++;
        }
        $result = call_user_func_array('\mysqli_stmt_bind_result', $fields);
        if (!$result) {
            throw new \Module\Exception\MySQL($this);
        }
    }
}